// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqfzycvxrhlqfgnrwdqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xZnp5Y3Z4cmhscWZnbnJ3ZHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDc1ODAsImV4cCI6MjA2OTI4MzU4MH0.uvtHgjhW66OQJ6vrEDURzXEQqABXprG2NW-XSM8P0n8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});